/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package dev.kafka.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class SecurityAction extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8758923245584795683L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SecurityAction\",\"namespace\":\"dev.kafka.avro\",\"fields\":[{\"name\":\"actionId\",\"type\":\"string\"},{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"actionType\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SecurityAction> ENCODER =
      new BinaryMessageEncoder<SecurityAction>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SecurityAction> DECODER =
      new BinaryMessageDecoder<SecurityAction>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SecurityAction> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SecurityAction> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SecurityAction> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SecurityAction>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SecurityAction to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SecurityAction from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SecurityAction instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SecurityAction fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence actionId;
  private java.lang.CharSequence userId;
  private java.lang.CharSequence actionType;
  private long timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SecurityAction() {}

  /**
   * All-args constructor.
   * @param actionId The new value for actionId
   * @param userId The new value for userId
   * @param actionType The new value for actionType
   * @param timestamp The new value for timestamp
   */
  public SecurityAction(java.lang.CharSequence actionId, java.lang.CharSequence userId, java.lang.CharSequence actionType, java.lang.Long timestamp) {
    this.actionId = actionId;
    this.userId = userId;
    this.actionType = actionType;
    this.timestamp = timestamp;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return actionId;
    case 1: return userId;
    case 2: return actionType;
    case 3: return timestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: actionId = (java.lang.CharSequence)value$; break;
    case 1: userId = (java.lang.CharSequence)value$; break;
    case 2: actionType = (java.lang.CharSequence)value$; break;
    case 3: timestamp = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'actionId' field.
   * @return The value of the 'actionId' field.
   */
  public java.lang.CharSequence getActionId() {
    return actionId;
  }


  /**
   * Sets the value of the 'actionId' field.
   * @param value the value to set.
   */
  public void setActionId(java.lang.CharSequence value) {
    this.actionId = value;
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.CharSequence getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.CharSequence value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'actionType' field.
   * @return The value of the 'actionType' field.
   */
  public java.lang.CharSequence getActionType() {
    return actionType;
  }


  /**
   * Sets the value of the 'actionType' field.
   * @param value the value to set.
   */
  public void setActionType(java.lang.CharSequence value) {
    this.actionType = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Creates a new SecurityAction RecordBuilder.
   * @return A new SecurityAction RecordBuilder
   */
  public static dev.kafka.avro.SecurityAction.Builder newBuilder() {
    return new dev.kafka.avro.SecurityAction.Builder();
  }

  /**
   * Creates a new SecurityAction RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SecurityAction RecordBuilder
   */
  public static dev.kafka.avro.SecurityAction.Builder newBuilder(dev.kafka.avro.SecurityAction.Builder other) {
    if (other == null) {
      return new dev.kafka.avro.SecurityAction.Builder();
    } else {
      return new dev.kafka.avro.SecurityAction.Builder(other);
    }
  }

  /**
   * Creates a new SecurityAction RecordBuilder by copying an existing SecurityAction instance.
   * @param other The existing instance to copy.
   * @return A new SecurityAction RecordBuilder
   */
  public static dev.kafka.avro.SecurityAction.Builder newBuilder(dev.kafka.avro.SecurityAction other) {
    if (other == null) {
      return new dev.kafka.avro.SecurityAction.Builder();
    } else {
      return new dev.kafka.avro.SecurityAction.Builder(other);
    }
  }

  /**
   * RecordBuilder for SecurityAction instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SecurityAction>
    implements org.apache.avro.data.RecordBuilder<SecurityAction> {

    private java.lang.CharSequence actionId;
    private java.lang.CharSequence userId;
    private java.lang.CharSequence actionType;
    private long timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(dev.kafka.avro.SecurityAction.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.actionId)) {
        this.actionId = data().deepCopy(fields()[0].schema(), other.actionId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.userId)) {
        this.userId = data().deepCopy(fields()[1].schema(), other.userId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.actionType)) {
        this.actionType = data().deepCopy(fields()[2].schema(), other.actionType);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing SecurityAction instance
     * @param other The existing instance to copy.
     */
    private Builder(dev.kafka.avro.SecurityAction other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.actionId)) {
        this.actionId = data().deepCopy(fields()[0].schema(), other.actionId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.userId)) {
        this.userId = data().deepCopy(fields()[1].schema(), other.userId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.actionType)) {
        this.actionType = data().deepCopy(fields()[2].schema(), other.actionType);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'actionId' field.
      * @return The value.
      */
    public java.lang.CharSequence getActionId() {
      return actionId;
    }


    /**
      * Sets the value of the 'actionId' field.
      * @param value The value of 'actionId'.
      * @return This builder.
      */
    public dev.kafka.avro.SecurityAction.Builder setActionId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.actionId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'actionId' field has been set.
      * @return True if the 'actionId' field has been set, false otherwise.
      */
    public boolean hasActionId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'actionId' field.
      * @return This builder.
      */
    public dev.kafka.avro.SecurityAction.Builder clearActionId() {
      actionId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public dev.kafka.avro.SecurityAction.Builder setUserId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.userId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public dev.kafka.avro.SecurityAction.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'actionType' field.
      * @return The value.
      */
    public java.lang.CharSequence getActionType() {
      return actionType;
    }


    /**
      * Sets the value of the 'actionType' field.
      * @param value The value of 'actionType'.
      * @return This builder.
      */
    public dev.kafka.avro.SecurityAction.Builder setActionType(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.actionType = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'actionType' field has been set.
      * @return True if the 'actionType' field has been set, false otherwise.
      */
    public boolean hasActionType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'actionType' field.
      * @return This builder.
      */
    public dev.kafka.avro.SecurityAction.Builder clearActionType() {
      actionType = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public dev.kafka.avro.SecurityAction.Builder setTimestamp(long value) {
      validate(fields()[3], value);
      this.timestamp = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public dev.kafka.avro.SecurityAction.Builder clearTimestamp() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SecurityAction build() {
      try {
        SecurityAction record = new SecurityAction();
        record.actionId = fieldSetFlags()[0] ? this.actionId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.userId = fieldSetFlags()[1] ? this.userId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.actionType = fieldSetFlags()[2] ? this.actionType : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.timestamp = fieldSetFlags()[3] ? this.timestamp : (java.lang.Long) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SecurityAction>
    WRITER$ = (org.apache.avro.io.DatumWriter<SecurityAction>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SecurityAction>
    READER$ = (org.apache.avro.io.DatumReader<SecurityAction>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.actionId);

    out.writeString(this.userId);

    out.writeString(this.actionType);

    out.writeLong(this.timestamp);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.actionId = in.readString(this.actionId instanceof Utf8 ? (Utf8)this.actionId : null);

      this.userId = in.readString(this.userId instanceof Utf8 ? (Utf8)this.userId : null);

      this.actionType = in.readString(this.actionType instanceof Utf8 ? (Utf8)this.actionType : null);

      this.timestamp = in.readLong();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.actionId = in.readString(this.actionId instanceof Utf8 ? (Utf8)this.actionId : null);
          break;

        case 1:
          this.userId = in.readString(this.userId instanceof Utf8 ? (Utf8)this.userId : null);
          break;

        case 2:
          this.actionType = in.readString(this.actionType instanceof Utf8 ? (Utf8)this.actionType : null);
          break;

        case 3:
          this.timestamp = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










