
services:
  postgres:
    image: postgres:15
    container_name: postgres_sport_db
    restart: always
    environment:
      POSTGRES_DB: sport_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sport_db"]
      interval: 5s
      timeout: 2s
      retries: 20

networks:
  postgres_network:
    driver: bridge

volumes:
  postgres_data: