server:
  port: 8686

spring:
  application:
    name: Gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: member-service
          uri: http://localhost:8568
          predicates:
            - Path=/members/**
        - id: security-service
          uri: http://localhost:8531
          predicates:
            - Path=/security/**
        - id: sport-service
          uri: http://localhost:8577
          predicates:
            - Path=/sport/**
